### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kennu** [cloudregistry/eppy#2]
I'm facing a situation where I need to connect to an EPP server that requires connections from a fixed IP address. I could do this by configuring a HTTP proxy, but is there any way to tell eppy to use the proxy?

**Comment by wil** [comment]
Hi Kenneth, what you need is a TCP proxy that listens to connections on that fixed IP, and forwards them to the EPP server. If you really want to use a HTTP, it will not be EPP anymore, and you'll need support on your HTTP proxy side, and build a client on top of `eppy` in order to speak your custom EPP-over-HTTP protocol.

**Comment by kennu** [comment]
Thanks, I did not at first realize that EPP is based on its own transport protocol rather than HTTP.

I was able to configure a proxy server by patching Python sockets with PySocks like this:

    pip install PySocks

    import os
    import socks
    import socket
    socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, os.environ['SOCKS_PROXY_HOST'], int(os.environ['SOCKS_PROXY_PORT']))
    socket.socket = socks.socksocket

PySocks also supports PROXY_TYPE_SOCKS4 and PROXY_TYPE_SOCKS5 but I already had Squid running, and PROXY_TYPE_HTTP works with Squid's CONNECT method.

**Comment by wil** [comment]
I'm glad that you found a solution, and a clever one too!

One word of caution - I'm not sure how well can PySocks patch the SSL calls. At least, some folks seem to have [encountered issues with it](https://github.com/Anorov/PySocks/issues/29).
